---
--- LoyalGuard.LGPrivilege
---
CREATE TABLE LGPrivilege (
	LGPrivilegeId INTEGER PRIMARY KEY AUTOINCREMENT
	, LGAccountId INTEGER
	, Starts TIMESTAMP
	, Ends TIMESTAMP
	, FeatureIdRef INTEGER
	, AbilityIdRef INTEGER
	, FOREIGN KEY (LGAccountId) REFERENCES LGAccount(LGAccountId) ON DELETE CASCADE
	, FOREIGN KEY (FeatureIdRef) REFERENCES LGFeature(LGFeatureId) ON DELETE SET NULL
	, FOREIGN KEY (AbilityIdRef) REFERENCES LGAbility(LGAbilityId) ON DELETE SET NULL
);
---
